---
- name: GROUPS | Add additional groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    system: "{{ item.system | default('false') }}"
  loop: "{{ anro_server_groups }}"
  loop_control:
    label: "{{ item.name }}"
