---
- name: Gather facts
  ansible.builtin.import_tasks: facts_vars.yaml
  tags:
    - always

- name: Set system hostname and kernel parameters
  become: true
  ansible.builtin.import_tasks: system.yaml
  tags:
    - server
    - server-system

- name: Configure baseline packages
  ansible.builtin.import_tasks: packages.yaml
  tags:
    - server
    - server-packages

- name: Set system timezone and time synchronization
  become: true
  ansible.builtin.import_tasks: time.yaml
  tags:
    - server
    - server-time

- name: Configure groups
  become: true
  ansible.builtin.import_tasks: groups.yaml
  tags:
    - server
    - server-groups

- name: Configure users
  become: true
  ansible.builtin.import_tasks: users.yaml
  tags:
    - server
    - server-users

- name: Configure mounts
  become: true
  when:
    - anro_server_mounts
    - anro_server_mounts | length > 0
  ansible.builtin.import_tasks: mounts.yaml
  tags:
    - server
    - server-mounts

- name: Configure authorized_keys
  ansible.builtin.import_tasks: authorized_keys.yaml
  tags:
    - server
    - server-keys

- name: Configure services
  when:
    - ansible_facts['service_mgr'] == 'systemd'
    - anro_server_services is defined
    - anro_server_services | length > 0
  ansible.builtin.import_tasks: services.yaml
  tags:
    - server
    - server-services

- name: Configure MOTD
  become: true
  ansible.builtin.import_tasks: motd.yaml
  tags:
    - server
    - server-motd

- name: Configure SNMPD
  ansible.builtin.import_tasks: snmpd.yaml
  tags:
    - server
    - server-snmpd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
