---
- name: MOTD | Add custom motd
  ansible.builtin.template:
    src: 99-user-motd.j2
    dest: /etc/update-motd.d/99-user-motd
    mode: '0755'

- name: MOTD | Ensure file /etc/motd exists
  ansible.builtin.file:
    dest: /etc/motd
    mode: '0755'
    state: touch
    modification_time: preserve
    access_time: preserve
