---
- name: PACKAGES | Set apt mirror on ubuntu
  when:
    - anro_server_set_mirror
    - ansible_distribution | lower == 'ubuntu'
  ansible.builtin.template:
    src: sources.list.ubuntu.j2
    dest: /etc/apt/sources.list
    backup: true
    mode: '0644'

- name: PACKAGES | Update apt package list
  when: ansible_pkg_mgr == 'apt'
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 10800
  changed_when: false
  failed_when: false

- name: PACKAGES | Update yum/dnf package list
  when: ansible_pkg_mgr == 'dnf'
  ansible.builtin.dnf:
    update_cache: true
  changed_when: false

- name: PACKAGES | Ensure python3 is installed
  ansible.builtin.package:
    state: present
    name: python3

- name: PACKAGES | Install packages
  when:
    - anro_server_add_packages is defined
    - anro_server_add_packages | length > 0
  ansible.builtin.package:
    state: present
    name: "{{ anro_server_add_packages | flatten }}"

- name: PACKAGES | Remove unwanted packages
  when:
    - anro_server_remove_packages is defined
    - anro_server_remove_packages | length > 0
  ansible.builtin.package:
    state: absent
    name: "{{ anro_server_remove_packages | flatten }}"
