---
- name: SYSTEM | Set system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: SYSTEM | Configure kernel parameters
  when:
    - anro_server_kernel_parameters
    - anro_server_kernel_parameters | length > 0
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value | default('') }}"
    state: "{{ item.state | default('present') }}"
    reload: "{{ item.reload | default(true) }}"
    sysctl_file: "{{ item.sysctl_file | default('/etc/sysctl.d/90-ansible.conf') }}"
    sysctl_set: "{{ item.sysctl_set | default(true) }}"
    ignoreerrors: "{{ item.ignoreerrors | default(false) }}"
  loop: "{{ anro_server_kernel_parameters }}"
  loop_control:
    label: "{{ item.name }}"
